prefix-dev/shell

crates/shell/src/main.rs
Temporarily fix exiting on syntax error in interactive shell as mentioned in #33. This will be updated upon miette support.
=> Fix exit on syntax error

crates/deno_task_shell/src/shell/commands/cd.rs
Fixes #32
```console
% cargo r
Compiling deno_task_shell v0.17.0 (/Users/pranavchiku/repos/shell/crates/deno_task_shell)
Compiling shell v0.1.0 (/Users/pranavchiku/repos/shell/crates/shell)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.12s
Running `target/debug/shell`
~/repos/shell$ cd
~$ ls
[...]
```
=> feat: support empty cd to go to the home directory

.github/workflows/rust-tests.yml, crates/deno_task_shell/src/shell/execute.rs, crates/deno_task_shell/src/shell/test.rs, typos.toml
Also add todo, that we should test everything
=> ci: fix typos in deno task shell

crates/shell/src/completion.rs, crates/shell/src/main.rs
We should actually potentially implement something like `hash` so that we have a hashmap of all the available executables instead of walking the filesystem on every completion. 
Then one would have to explicitly "rehash" though.
=> feat: add auto-completion

Cargo.lock, crates/deno_task_shell/Cargo.toml, crates/deno_task_shell/src/parser.rs, crates/shell/src/main.rs
This allows to print the parse tree when doing `cargo r -- -f script.sh -d`
=> feat: add debug mode

crates/deno_task_shell/src/shell/types.rs, crates/shell/src/main.rs
We keep track of if we are inside a git repository inside the ShellState struct as well as if the branch was updated in the last command. In the main loop we then update the branch name if it wasn't already updated, and then show the branch in the prompt if we are inside a repository.
We only visit `.git/HEAD` once per `set_cwd()` call and we only run again in the main loop if we did not run in that iteration yet.
However I discovered that the `set_cwd()` call is being called twice in every iteration for some reason, and so we also read `.git/HEAD` twice. This is a separate issue so it should be fixed in a separate PR once this is merged.
=> Implement showing of git branch in the prompt

Cargo.lock, crates/shell/Cargo.toml, crates/shell/src/completion.rs, crates/shell/src/helper.rs, crates/shell/src/main.rs
@certik – I think this works! :)
=> Color prompt

crates/deno_task_shell/src/shell/commands/cat.rs
If the file does not end with a newline, the last line was swallowed. 
This mimicks what cat on macOS is doing by printing a `%\n` at the end of cat'ting when in interactive mode. On macOS this is a white-on-black percentage sign, which would be a small improvement. 
Not sure if theoretically this should be handled by the shell or cat, though. 
In order to implement this on the shell level we would need to redirect the stdout stream and inspect it.
=> print last line when cat-ting interactively

crates/shell/src/main.rs
That's also how other shells work
Fixes #96
=> fix: make `file` argument positional

crates/deno_task_shell/src/shell/execute.rs, crates/deno_task_shell/src/shell/types.rs, crates/shell/src/commands.rs, crates/shell/src/main.rs
This is a beginning of a pretty straightforward `alias` function. Alias just substitutes the first arg in a list of args if there is a match.
=> implement alias

crates/shell/src/commands.rs, crates/shell/src/execute.rs, crates/shell/src/main.rs
Fixes #94.
I am not sure about the exact semantics. Currently, everything that is modified in the sourced' script is also going to be modified in the parent script.
=> feat: implement `source`

Cargo.lock, crates/deno_task_shell/Cargo.toml, crates/deno_task_shell/src/parser.rs, crates/deno_task_shell/src/shell/command.rs, crates/shell/src/execute.rs
This implements basic migration miette. #77 
Pest uses miette for error reporting now - this has been fixed. 
The rest of the errors do not implement miette's fancy features. I want to use the fancy features for errors created on ast level. 
I will implement those in a separate PR. 
Closes #86
=> Switch to miette for error reporting

crates/shell/src/main.rs
This only fixes pressing Ctrl-C on the command-line itself, not while running another program.
=> Do not exit the shell on Ctrl-C

Cargo.lock, crates/shell/Cargo.toml, crates/shell/src/commands/date.rs, crates/shell/src/commands/mod.rs, crates/tests/src/lib.rs
Closes #146 
It uses `uu_date` to handle date command. However, I noticed it does not support commands like:
`date -r Cargo.toml`. I will open a PR soon to `uu_date` to add support for this.
=> feat Add date support

crates/shell/src/main.rs
This is how Bash behaves, it is a lot more natural.
Fixes #99.
=> Use CompletionType::List

Cargo.lock, crates/shell/Cargo.toml, crates/shell/src/main.rs
This allows to catch Ctrl-C from within a running command, but unfortunately still exits. Also there seems to be some thread (?) still running in the background, since I get some later error message while I am already back in Bash:
```console
~/repos/shell(ctrl_c2)$ cat
^CReceived Ctrl+C
~/repos/shell(ctrl_c2)$ cat: Input/output error (os error 5)
Error: Errno(EIO)
~/repos/shell(ctrl_c2)$
```
Fixes #120.
=> Set Ctrl-C signal handler

crates/deno_task_shell/src/grammar.pest, crates/tests/src/lib.rs, crates/tests/src/test_builder.rs, scripts/if_else.sh
=> fix Correct if syntax

crates/shell/src/main.rs
=> Source ~/.shellrc automatically if it exists

crates/shell/src/main.rs
This agrees with the default prompt in `zsh` on macOS, and it seems less distracting than the red color, which seems to suggest some error state.
Towards #187.
=> Use green default color for git prompt

crates/deno_task_shell/src/shell/commands/cat.rs
Currently the % is printed in every batch of 1024 characters if they don't end with a new line. Instead, we only print % at the very end if needed.
Fixes #195.
=> cat: only print % at the very end if needed

crates/shell/src/main.rs
This is just an initial support, so far only two templates are supported, using a custom format. Later, we should use some templating engine, and consider compatibility with either Bash or with Zsh.
Fixes #200.
=> Implement prompt templating support via $PS1

crates/shell/src/main.rs
Handle exit code correctly. Use it like this:
$ shell -c "echo 'ok'"
ok
$ echo $?
0
$ shell -c "echox 'ok'"
echox: command not found
$ echo $?
127
Fixes #211.
=> Add a -c option to execute a command

crates/shell/src/commands/mod.rs, crates/shell/src/main.rs
fixes https://github.com/prefix-dev/shell/issues/203
also fixes https://github.com/prefix-dev/shell/issues/205
=> feat: support `.` as alias for source

Cargo.lock, crates/deno_task_shell/src/grammar.pest, crates/shell/Cargo.toml, crates/shell/src/commands/mod.rs, crates/shell/src/commands/time.rs
I have implemented a basic implementation for adding `time` to shell but not sure about the behaviour on Windows. @certik Can you please check this on Windows?
=> Add support for `time`

.github/workflows/coverage.yml, .github/workflows/enforce-sha.yaml, .github/workflows/release.yml, .github/workflows/rust-linting.yml, .github/workflows/rust-tests.yml, .github/workflows/typos.yml
- pin external actions
- enforce sha also in the future
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/
=> ci: pin github actions

.github/workflows/coverage.yml
Currently, it triggers coverage run on each commit push.
Ex: https://github.com/kp992/shell/actions
cc @wolfv.
=> Run coverage only on main and tags

crates/deno_task_shell/src/grammar.pest, crates/tests/src/lib.rs
=> fix: reserved word substrings
